# Generated by Django 4.1.4 on 2023-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
