# Generated by Django 4.1.4 on 2023-01-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_user_auto_copy_previous_user_auto_update_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="edited",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
