# Generated by Django 4.1.4 on 2023-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="steps",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
