# Generated by Django 4.1.4 on 2023-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_alter_metrics_id_alter_metrics_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="bodyweight",
            field=models.FloatField(default=None, null=True),
        ),
    ]
