# Generated by Django 4.1.4 on 2023-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_remove_user_yesterday_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fiber_goal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
