# Generated by Django 4.1.4 on 2023-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_user_fiber_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auto_copy_previous",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="auto_update_steps",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
