# Generated by Django 4.1.4 on 2023-01-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_user_last_step_sync_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metrics',
            unique_together={('account', 'date')},
        ),
    ]
