# Generated by Django 4.1.4 on 2023-01-31 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0008_alter_user_auto_copy_previous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auto_copy_previous",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="auto_update_steps",
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(verbose_name=1000)),
                (
                    "subbed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
