# Generated by Django 4.1.4 on 2023-02-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0009_alter_user_auto_copy_previous_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(null=True),
        ),
    ]
