# Generated by Django 4.1.4 on 2023-01-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_metrics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='calories',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
