# Generated by Django 4.1.4 on 2023-02-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0010_user_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customernumber",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
