# Generated by Django 4.1.4 on 2023-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_metrics_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='contents',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
