# Generated by Django 4.1.4 on 2023-02-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0013_remove_user_subscriptionnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="checkout_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
